import { Book } from "../model";

export const books: Book[] = [
  {
    "id": 1,
    "imgurl": "https://m.media-amazon.com/images/I/41vMedR4cFL._SY445_SX342_PQ37_.jpg",
    "title": "The Dancer",
    "author": "Olivia Wilson",
    "ratings": 4.5,
    "price": 50,
    "pages": 352,
    "language": "English",
    "publisher": "Bloomsbury Publishing",
    "publication_date": "2023-06-15",
    "category": "Fiction",
    "discount": 0.10
  },
  {
    "id": 2,
    "imgurl": "https://m.media-amazon.com/images/I/41kG0dpKr9L._SY445_SX342_PQ37_.jpg",
    "title": "The Devil's Fortress",
    "author": "Dale Brown",
    "ratings": 4.8,
    "price": 40,
    "pages": 420,
    "language": "English",
    "publisher": "Penguin Random House",
    "publication_date": "2024-10-27",
    "category": "Thriller",
    "discount": 0.20
  },
  {
    "id": 3,
    "imgurl": "https://m.media-amazon.com/images/I/419CqGgAdZL._SY445_SX342_.jpg",
    "title": "The Woods",
    "author": "Sebastian Bennett",
    "ratings": 4.2,
    "price": 70,
    "pages": 288,
    "language": "English",
    "publisher": "HarperCollins",
    "publication_date": "2022-03-12",
    "category": "Mystery",
    "discount": 0
  },
  {
    "id": 4,
    "imgurl": "https://m.media-amazon.com/images/I/41LvUU4TOiL._SY445_SX342_PQ37_.jpg",
    "title": "Be Yourself",
    "author": "Kimberly Nguyen",
    "ratings": 4.6,
    "price": 50,
    "pages": 224,
    "language": "English",
    "publisher": "Hay House",
    "publication_date": "2021-09-01",
    "category": "Self-Help",
    "discount": 0.15
  },
  {
    "id": 5,
    "imgurl": "https://m.media-amazon.com/images/I/41vMedR4cFL._SY445_SX342_PQ37_.jpg",
    "title": "Nostalgia Calling",
    "author": "Bailey Dupont",
    "ratings": 4.7,
    "price": 70,
    "pages": 384,
    "language": "English",
    "publisher": "Sourcebooks",
    "publication_date": "2020-11-17",
    "category": "Romance",
    "discount": 0.05
  },
  {
    "id": 6,
    "imgurl": "https://m.media-amazon.com/images/I/419CqGgAdZL._SY445_SX342_.jpg",
    "title": "Nostalgia Calling",
    "author": "Bailey Dupont",
    "ratings": 4.7,
    "price": 70,
    "pages": 384,
    "language": "English",
    "publisher": "Sourcebooks",
    "publication_date": "2020-11-17",
    "category": "Romance",
    "discount": 0.05
  },
  {
    "id": 7,
    "imgurl": "https://m.media-amazon.com/images/I/41kG0dpKr9L._SY445_SX342_PQ37_.jpg",
    "title": "Silent Whispers",
    "author": "Mark Thompson",
    "ratings": 4.1,
    "price": 55,
    "pages": 304,
    "language": "English",
    "publisher": "Simon & Schuster",
    "publication_date": "2023-01-24",
    "category": "Suspense",
    "discount": 0.25
  },
  {
    "id": 8,
    "imgurl": "https://m.media-amazon.com/images/I/41vMedR4cFL._SY445_SX342_PQ37_.jpg",
    "title": "Path of Shadows",
    "author": "Isabella Harper",
    "ratings": 4.9,
    "price": 60,
    "pages": 400,
    "language": "English",
    "publisher": "Orbit Books",
    "publication_date": "2022-07-05",
    "category": "Fantasy",
    "discount": 0.12
  },
  {
    "id": 9,
    "imgurl": "https://m.media-amazon.com/images/I/51jux4tZQqL._SY445_SX342_PQ37_.jpg",
    "title": "The Last Voyage",
    "author": "Robert Collins",
    "ratings": 4.4,
    "price": 50,
    "pages": 336,
    "language": "English",
    "publisher": "William Morrow",
    "publication_date": "2021-04-13",
    "category": "Adventure",
    "discount": 0.18
  },
  {
    "id": 11,
    "imgurl": "https://m.media-amazon.com/images/I/41vMedR4cFL._SY445_SX342_PQ37_.jpg",
    "title": "Shattered Dreams",
    "author": "James Knight",
    "ratings": 4.5,
    "price": 55,
    "pages": 256,
    "language": "English",
    "publisher": "Grand Central Publishing",
    "publication_date": "2020-08-18",
    "category": "Drama",
    "discount": 0.08
  },
  {
    "id": 12,
    "imgurl": "https://m.media-amazon.com/images/I/51jux4tZQqL._SY445_SX342_PQ37_.jpg",
    "title": "The Last Voyage",
    "author": "Robert Collins",
    "ratings": 4.4,
    "price": 50,
    "pages": 336,
    "language": "English",
    "publisher": "William Morrow",
    "publication_date": "2021-04-13",
    "category": "Adventure",
    "discount": 0.18
  },
  {
    "id": 14,
    "imgurl": "https://m.media-amazon.com/images/I/41vMedR4cFL._SY445_SX342_PQ37_.jpg",
    "title": "Shattered Dreams",
    "author": "James Knight",
    "ratings": 4.5,
    "price": 55,
    "pages": 256,
    "language": "English",
    "publisher": "Grand Central Publishing",
    "publication_date": "2020-08-18",
    "category": "Drama",
    "discount": 0.08
  }
]
